# Generated by Django 4.0.4 on 2022-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=1000)),
                ('k_name', models.CharField(max_length=20)),
                ('quant', models.IntegerField(default=3)),
                ('info', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
