# Generated by Django 4.0.4 on 2022-05-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('is_enter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('quant', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.product')),
            ],
        ),
    ]
