# Generated by Django 4.0.4 on 2022-05-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='detect_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
